# Generated by Django 5.2 on 2025-06-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_delete', 'can edit and delete for blog')]},
        ),
    ]
