# Generated by Django 5.2 on 2025-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_of_view',
            field=models.IntegerField(default=0),
        ),
    ]
